name: Check

# This workflow ensures code quality by running prettier formatting checks
# and TypeScript type checking on all pull requests
on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm & install
        uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: 22

      - name: Run type checking and formatting
        run: pnpm run check

      - name: Run unit tests
        run: pnpm run test:unit

      - name: Build
        run: pnpm build
